### ISSUE TITLE
Rename DQ_DifferentialDriveRobot to DQ_DifferentialDriveBase?

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#24]
Hello, @bvadorno,

**Context**
I was checking `DQ_DifferentialDriveRobot` and I noticed that its name contrasts with its parent classes:
```
DQ_MobileBase
DQ_HolonomicBase
```

**Question**

Is there any specific reason why this one became `Robot` instead of `Base`?

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, Murilo.

There is a reason, although very subtle. 'Mobile robot' is a very broad class of robots, which encompasses mobile bases, legged robots, etc., although it is common to use 'mobile robot' as a synonym of 'mobile base'. The same applies to 'holonomic robot'; for instance, a serial manipulator is a holonomic robot but with a fixed base! Therefore, I first decided to stick with DQ_MobileBase and DQ_HolonomicBase to be more precise. The name 'differential-drive **_robot_**', on the other hand, is unambiguous because it makes sense, AFAIK, only for mobile bases. Plus, the name 'differential-drive **_base_**' is very uncommon; this is why I chose the former.

Cheers,
Bruno
