### ISSUE TITLE
Renaming  jacobian() (and related functions/methods) to pose_jacobian()

### ISSUE THREAD

**Issue by mmmarinho** [dqrobotics/matlab#7]
Hello, Bruno,

**Context:** 
According to our latest decisions regarding function/method naming convention, the Jacobian-related method/functions names became
`jacobian()`
`raw_jacobian()`
`jacobian_derivative()`
`translation_jacobian()`
`rotation_jacobian()`
`distance_jacobian()`
and so on for possibly new Jacobians as well.

**Suggestion:**
Change  the following function/method names
from `jacobian()` to `pose_jacobian()` 
from `raw_jacobian()` to `raw_pose_jacobian()`
from `jacobian_derivative()` to `pose_jacobian_derivative()`

**Major reason:** 
It seems a bit strange that the pose Jacobian has some special status in the library, even more so considering the upcoming additions of the Jacobians related to distance primitives,
_Example:_ At first glance, a new user might think that `jacobian_derivative()` returns the derivative of any given Jacobian, when in fact it returns the derivative of a very specific Jacobian which is related to the robot's  pose.

What do you think?

Kind regards,
Murilo

**Comment by bvadorno** [comment]
Hi, Murilo.

Yes, in light of our established naming convention, it makes sense to rename those three methods. For the moment, I'll follow the strategy I was using before, that is, every renamed function has a corresponding legacy one, with the old name, in order to prevent breaking legacy code. However, those legacy functions emit a warning whenever they are used.

Cheers,
Bruno
